In [9]:
# 1. Create a constant number
import numpy as np
y=np.array([7.,7.,7.,7.])
y.resize([2,2])
y

array([[7., 7.],
       [7., 7.]])

In [17]:
# 2. Create an array filled with Random Numbers
ran = np.random.rand(2,2)
ran

array([[0.91796175, 0.43695082],
       [0.27583055, 0.04850518]])

In [16]:
# 3. Create a NumPy array containing the numbers from 10 to 50. Display
x = np.arange(10,51)
print(x) # Array
print(len(x)) # Number of elements
print(x.shape) #Shape
print(x.ndim) # Dimension 
print(type(x)) # Data Type

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
41
(41,)
1
<class 'numpy.ndarray'>


In [25]:
# 4. Create

# A 1D array containng 10 zeros
print(np.zeros((1,10)))
# 3x3 array containing ones
print(np.ones((3,3)))
#4x4 identity matrix
print(np.eye(4))
# Array containing numbers from 5 to 50 with step 5
steps = np.arange(5,51)
print(steps[::5])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[ 5 10 15 20 25 30 35 40 45 50]


In [31]:
# 5. Create an array containing numbers from 1 to 24. Reshape it into
x = np.arange(1,25)

# 4 x 6
x.resize(4,6)
print(x.shape)
print(x.ndim)

# 6 x 4
x.resize(6,4)
print(x.shape)
print(x.ndim)

# 2 x 3 x 4
x.resize(2,3,4)
print(x.shape)
print(x.ndim)

(4, 6)
2
(6, 4)
2
(2, 3, 4)
3


In [36]:
# 6.
marks = np.array([78,85,92,67,88,73,95,81])
# First element
print(marks[0])
# Last element
print(marks[-1])
# Third element
print(marks[2])
# First 4 elements
print(marks[0:4])
# Last 3 elements
print(marks[-3:])

78
81
92
[78 85 92 67]
[73 95 81]


In [37]:
# 7
a = np.array([10,20,30,40,50])
b = np.array([5,10,15,20,25])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)

[15 30 45 60 75]
[ 5 10 15 20 25]
[  50  200  450  800 1250]
[2. 2. 2. 2. 2.]
[ 100  400  900 1600 2500]


In [59]:
# 8. Given,
salary = np.array([25000, 32000, 28000, 45000, 50000, 38000, 42000, 30000])

#Total Salary
print(salary.sum())
#Average Salary
print(salary.mean())
#Highest Salary
print(salary.max())
#Lowest Salary
print(salary.min())
#Median Salary
print(np.median(salary))
#Standard Deviation
print(salary.std())

290000
36250.0
50000
25000
35000.0
8317.902379807063


In [49]:
# 9. Using NumPy indexing, find
marks = np.array([45,78,89,32,67,90,55,76,41,84]) 

# Marks greater than 75
print(marks[marks>75])

#Marks between 50 and 80
print(marks[(marks>=50) & (marks<=80)])

# No. of students who scored below 50
print(len(marks[marks<50]))

# Percentage of students who scored 60 or above
print(len(marks[marks>=60])*100 / len(marks))

[78 89 90 76 84]
[78 67 55 76]
3
60.0


In [64]:
# 10. Following array contains marks of four students in three subjects:
marks = np.array([
    [80,75,90],
    [65,70,72],
    [88,92,85],
    [55,60,58]
])

# total marks of each student
print("Total marks of Student 1:",marks[0].sum())
print("Total marks of Student 2:",marks[1].sum())
print("Total marks of Student 3:",marks[2].sum())
print("Total marks of Student 4:",marks[3].sum())

#Average marks of each student
print("Average marks of Student 1:",marks[0].mean())
print("Average marks of Student 2:",marks[1].mean())
print("Average marks of Student 3:",marks[2].mean())
print("Average marks of Student 4:",marks[3].mean())

#Average marks in each subject
print("Average marks in Subject 1:",marks[:,0].mean())
print("Average marks in Subject 2:",marks[:,1].mean())
print("Average marks in Subject 3:",marks[:,2].mean())

#Student with the highest total

#Highest marks in each subject
print("Highest marks in Subject 1:",marks[:,0].max())
print("Highest marks in Subject 2:",marks[:,1].max())
print("Highest marks in Subject 3:",marks[:,2].max())

Total marks of Student 1: 245
Total marks of Student 2: 207
Total marks of Student 3: 265
Total marks of Student 4: 173
Average marks of Student 1: 81.66666666666667
Average marks of Student 2: 69.0
Average marks of Student 3: 88.33333333333333
Average marks of Student 4: 57.666666666666664
Average marks in Subject 1: 72.0
Average marks in Subject 2: 74.25
Average marks in Subject 3: 76.25
Highest marks in Subject 1: 88
Highest marks in Subject 2: 92
Highest marks in Subject 3: 90


In [ ]:
# 11. Create:
A = np.array([
    [1,2],
    [3,4]
])
B = np.array([
    [5,6],
    [7,8]
])
#Matrix Addition
#Element wise mutiplication
#Matrix Multiplication
#Transpose of A

# Explain the differnce between: A * B and A @ B

In [68]:
# 12. Daily temperature for 2 weeks are:

temperature = np.array([
    31,32,33,35,36,34,32,
    30,29,31,33,35,37,36
])
#Mean temperature
print(temperature.mean())
# Maximum and Minimum Temperature
print(temperature.max())
print(temperature.min())
# No. of days above the average temperature
print(len(temperature[temperature>temperature.mean()]))
# Temperature greater than 34
print(temperature[temperature>34])
# Differnce between max and min
print(temperature.max() - temperature.min())
#Standard Deviation
print(temperature.std())

33.142857142857146
37
29
6
[35 36 35 37 36]
8
2.356060357495806


In [ ]:
# 13. Monthly