In [25]:
import numpy as np
y= np.array([4,5,6])
y

array([4, 5, 6])

In [8]:
n=np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
m=np.array([7,8,9],[10,11,12])

In [6]:
n=np.arange(30,0,-2)
n

array([30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [ ]:
# Returns an array with the same data with a new shape
n=n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [ ]:
#linspace returns evenly spaced numbers over a specified interval
lspace =np.linspace(0,10,9)
lspace

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [12]:
lspace.resize(3,3)
lspace

array([[ 0.  ,  1.25,  2.5 ],
       [ 3.75,  5.  ,  6.25],
       [ 7.5 ,  8.75, 10.  ]])

In [ ]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# Return a 2D array with ones in the diagonal
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
num=np.matrix([[11,121,130,457],
               [613,34,13,89],
               [514,15,16,89],
               [67,45,90,346]])

num

matrix([[ 11, 121, 130, 457],
        [613,  34,  13,  89],
        [514,  15,  16,  89],
        [ 67,  45,  90, 346]])

In [20]:
type(num)

numpy.matrix

In [23]:
print("Main Diagonal elements :\n", np.diag(num))
print("\nDiagonal elements above main diagonal : \n",np.diag(num,1))
print("\nDiagonal elements below main diagonal : \n",np.diag(num,-1))

Main Diagonal elements :
 [ 11  34  16 346]

Diagonal elements above main diagonal : 
 [121  13  89]

Diagonal elements below main diagonal : 
 [613  15  90]


In [24]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [ ]:
p=np.ones([3,3],int) #By default the type is float
p

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
#stack array in sequence vertically (row wise)
np.vstack([p,2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [28]:
np.vstack([p,2*p,3*p])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [29]:
np.hstack([p,p*2])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [30]:
np.hstack([p,2*p,3*p])

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [1, 1, 1, 2, 2, 2, 3, 3, 3],
       [1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [4]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x@y)
print(x**y)
print(x**2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
32
[  1  32 729]
[1 4 9]


In [ ]:
x.dot(y)

np.int64(32)

In [6]:
y.dot(x)

np.int64(32)

In [7]:
z = np.array([y,y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [ ]:
print(len(z)) # Number of rows of the array

2


In [ ]:
z.shape #Gives rows and columns

(2, 3)

In [ ]:
z.T # To get transpose of the array

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [11]:
z.T.shape

(3, 2)

In [ ]:
z.dtype

dtype('int64')

In [13]:
z = z.astype('f')
z.dtype

dtype('float32')

In [14]:
a=np.array([-4,-2,1,3,5])
a.sum()

np.int64(3)

In [15]:
a.max()

np.int64(5)

In [16]:
a.min()

np.int64(-4)

In [17]:
a.mean()

np.float64(0.6)

In [ ]:
a.std() #std^ = Sum Xi-Xmean/N

np.float64(3.2619012860600183)

In [19]:
a.argmax()

np.int64(4)

In [20]:
a.argmin()

np.int64(0)

In [33]:
s=np.arange(100)
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [31]:
s.reshape([10,10])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [34]:
import numpy as np
s=np.arange(6)**2
s

array([ 0,  1,  4,  9, 16, 25])

In [35]:
s[0],s[4],s[-1]

(np.int64(0), np.int64(16), np.int64(25))

In [36]:
s[1:5]

array([ 1,  4,  9, 16])

In [37]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [38]:
s[0],s[4],s[-1]

(np.int64(0), np.int64(16), np.int64(144))

In [39]:
s[-4:]

array([ 81, 100, 121, 144])

In [40]:
s[-5::-2]

array([64, 36, 16,  4,  0])

In [41]:
s[-5:-2]

array([ 64,  81, 100])

In [44]:
r=np.arange(100)
r.resize([10,10])

In [45]:
r[3,4]

np.int64(34)

In [46]:
r[2,1:4]

array([21, 22, 23])

In [47]:
r[3,3:6]

array([33, 34, 35])

In [49]:
r[:3,::-1]

array([[ 9,  8,  7,  6,  5,  4,  3,  2,  1,  0],
       [19, 18, 17, 16, 15, 14, 13, 12, 11, 10],
       [29, 28, 27, 26, 25, 24, 23, 22, 21, 20]])

In [50]:
r[-1,::2]

array([90, 92, 94, 96, 98])

In [51]:
r[r>30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
       65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
       82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,
       99])

In [53]:
r[r>30] = 30
r

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30]])

In [54]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [56]:
r2[:]=0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [57]:
r

array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30]])

In [58]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30]])

In [60]:
r_copy[:] = 10
print(r_copy, "\n")
print(r)

[[10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5  6  7  8  9]
 [ 0  0  0 13 14 15 16 17 18 19]
 [ 0  0  0 23 24 25 26 27 28 29]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]]


In [61]:
test = np.random.randint(0,10,(4,3))
test

array([[2, 4, 2],
       [3, 1, 6],
       [0, 3, 2],
       [1, 9, 2]], dtype=int32)

In [64]:
# Iterate by the row
for row in test:
    print(row)

[2 4 2]
[3 1 6]
[0 3 2]
[1 9 2]


In [66]:
for i, row in enumerate(test):
    print('row',i,'is',row)


row 0 is [2 4 2]
row 1 is [3 1 6]
row 2 is [0 3 2]
row 3 is [1 9 2]


In [ ]:
#Use zip to iterate over multiple iterables
test2 =test**2
test2

array([[ 4, 16,  4],
       [ 9,  1, 36],
       [ 0,  9,  4],
       [ 1, 81,  4]], dtype=int32)

In [69]:
for i,j in zip(test,test2):
    print(i,'+',j,'=',i+j)

[2 4 2] + [ 4 16  4] = [ 6 20  6]
[3 1 6] + [ 9  1 36] = [12  2 42]
[0 3 2] + [0 9 4] = [ 0 12  6]
[1 9 2] + [ 1 81  4] = [ 2 90  6]


In [ ]:
marks = np.array([
    [80,75,98],
    [65,70,72],
    [88,92,85],
    [55,68,58]
])

student_total = np.sum(marks, axis = 1)
print("Total of each student:", student_total)

student_average = np.mean(marks, student_total)
print("Average of each student: ",student_average)

print("Average of each subject")

highest_student = np.argmax(student_total)
print("")

highest_subject = np.max(marks,axis=0)
print("Highest marks in each subject")