In [4]:
# 1. Create a constant number
import numpy as np
constant_array=np.array([7.,7.,7.,7.])
constant_array.resize([2,2])
print(constant_array)

[[7. 7.]
 [7. 7.]]


In [6]:
# 2. Create an array filled with Random Numbers
random_array = np.random.rand(2,2)
print(random_array)

[[0.86435314 0.35713738]
 [0.78000988 0.37646521]]


In [7]:
# 3. Create a NumPy array containing the numbers from 10 to 50. Display
range_array = np.arange(10,51)
print(range_array) # Array
print(range_array.size) # Number of elements
print(range_array.shape) #Shape
print(range_array.ndim) # Dimension 
print(type(range_array)) # Data Type

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
41
(41,)
1
<class 'numpy.ndarray'>


In [8]:
# 4. Create

# A 1D array containng 10 zeros
print(np.zeros(10))
# 3x3 array containing ones
print(np.ones((3,3)))
#4x4 identity matrix
print(np.eye(4))
# Array containing numbers from 5 to 50 with step 5
print(np.arange(5,51,5))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[ 5 10 15 20 25 30 35 40 45 50]


In [12]:
# 5. Create an array containing numbers from 1 to 24. Reshape it into
array_5 = np.arange(1,25)

# 4 x 6
new_array_5=array_5.reshape(4,6)
print(new_array_5.shape)
print(new_array_5.ndim)

# 6 x 4
new_array_5=array_5.reshape(6,4)
print(new_array_5.shape)
print(new_array_5.ndim)

# 2 x 3 x 4
new_array_5=array_5.reshape(2,3,4)
print(new_array_5.shape)
print(new_array_5.ndim)

(4, 6)
2
(6, 4)
2
(2, 3, 4)
3


In [ ]:
# 6.
marks = np.array([78,85,92,67,88,73,95,81])
# First element
print(marks[0])
# Last element
print(marks[-1])
# Third element
print(marks[2])
# First 4 elements
print(marks[:4])
# Last 3 elements
print(marks[-3:])

78
81
92
[78 85 92 67]
[73 95 81]


In [13]:
# 7
a = np.array([10,20,30,40,50])
b = np.array([5,10,15,20,25])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)

[15 30 45 60 75]
[ 5 10 15 20 25]
[  50  200  450  800 1250]
[2. 2. 2. 2. 2.]
[ 100  400  900 1600 2500]


In [59]:
# 8. Given,
salary = np.array([25000, 32000, 28000, 45000, 50000, 38000, 42000, 30000])

#Total Salary
print(salary.sum())
#Average Salary
print(salary.mean())
#Highest Salary
print(salary.max())
#Lowest Salary
print(salary.min())
#Median Salary
print(np.median(salary))
#Standard Deviation
print(salary.std())

290000
36250.0
50000
25000
35000.0
8317.902379807063


In [49]:
# 9. Using NumPy indexing, find
marks = np.array([45,78,89,32,67,90,55,76,41,84]) 

# Marks greater than 75
print(marks[marks>75])

#Marks between 50 and 80
print(marks[(marks>=50) & (marks<=80)])

# No. of students who scored below 50
print(len(marks[marks<50]))

# Percentage of students who scored 60 or above
print(len(marks[marks>=60])*100 / len(marks))

[78 89 90 76 84]
[78 67 55 76]
3
60.0


In [14]:
# 10. Following array contains marks of four students in three subjects:
marks = np.array([
    [80,75,90],
    [65,70,72],
    [88,92,85],
    [55,60,58]
])

print("Total marks per student:", np.sum(marks, axis=1))
print("Average marks per student:", np.mean(marks, axis=1))
print("Average marks per subject:", np.mean(marks, axis=0))
print("Student with highest total (index):", np.argmax(np.sum(marks, axis=1)))
print("Highest mark per subject:", np.max(marks, axis=0))

Total marks per student: [245 207 265 173]
Average marks per student: [81.66666667 69.         88.33333333 57.66666667]
Average marks per subject: [72.   74.25 76.25]
Student with highest total (index): 2
Highest mark per subject: [88 92 90]


In [ ]:
# 11. Create:
A = np.array([
    [1,2],
    [3,4]
])
B = np.array([
    [5,6],
    [7,8]
])
#Matrix Addition
print(A + B)
#Element wise mutiplication
print(A * B)
#Matrix Multiplication
print(A @ B)
#Transpose of A
print(A.T)

# Explain the differnce between: A * B and A @ B
# A*B is element wise multiplication
# A@B is linear algebra matrix multiplication (dot product of rows and columns)

In [17]:
# 12. Daily temperature for 2 weeks are:

temperature = np.array([
    31,32,33,35,36,34,32,
    30,29,31,33,35,37,36
])
#Mean temperature
print(temperature.mean())
# Maximum and Minimum Temperature
print(temperature.max())
print(temperature.min())
# No. of days above the average temperature
print(len(temperature[temperature>temperature.mean()]))
# Temperature greater than 34
print(temperature[temperature>34])
# Differnce between max and min
print(temperature.max() - temperature.min())
#Standard Deviation
print(temperature.std())

33.142857142857146
37
29
6
[35 36 35 37 36]
8
2.356060357495806


In [19]:
# 13. Monthly sales of a company are:
sales = np.array([
    12000, 15000, 17000, 14000,
    18000, 21000, 19000, 22000,
    25000, 23000, 26000, 28000
])

#Total annual sales
print(np.sum(sales))
#Average monthly sales
print(np.mean(sales))
#Month with the highest sales
print(np.argmax(sales) + 1)
#Month with the lowest sales
print(np.argmin(sales) + 1)
#Number of months with sales above ₹20,000
print(np.sum(sales > 20000))
#Percentage increase from January to December
percent_increase = ((sales[-1] - sales[0]) / sales[0]) * 100
print(f'{percent_increase:.2f}%')

240000
20000.0
12
1
6
133.33%


In [35]:
#14. Consider marks of five students in four subjects:

import numpy as np

# Sample Data: 5 Students x 4 Subjects
marks = np.array([
    [78, 85, 90, 88],
    [65, 70, 72, 68],
    [92, 88, 95, 91],
    [55, 60, 58, 62],
    [80, 75, 82, 79]
])

# Total marks of every student
print(np.sum(marks, axis=1))
# Average of every student
student_averages = np.mean(marks, axis=1)
print(student_averages)
# Average mark for every subject
print(np.mean(marks, axis=0))
# Highest-scoring student (0-indexed position)
print(np.argmax(student_averages))
# Lowest-scoring student (0-indexed position)
print(np.argmin(student_averages))
# Students whose average is greater than 80 (indices/averages)
print(student_averages[student_averages > 80])
# Overall class average
print(np.mean(marks))
# Assign categories using np.select()
conditions = [
    student_averages >= 85,
    (student_averages >= 70) & (student_averages < 85),
    (student_averages >= 50) & (student_averages < 70),
    student_averages < 50
]
categories = ["Excellent", "Good", "Average", "Needs Improvement"]

performance_categories = np.select(conditions, categories,default="N/A")
print(performance_categories)


[341 275 366 235 316]
[85.25 68.75 91.5  58.75 79.  ]
[74.  75.6 79.4 77.6]
2
3
[85.25 91.5 ]
76.65
['Excellent' 'Average' 'Excellent' 'Average' 'Good']


In [23]:
# 15. Generate 20 random integers between 1 and 100.
rand_arr = np.random.randint(1, 101, size=20)
print(rand_arr)

[51 99 14 21 46 68 21 12 89 49 16 90 65 17 97 55 98 26 24 33]


In [24]:
# 16. Find all even numbers from the generated array.
print(rand_arr[rand_arr % 2 == 0])

[14 46 68 12 16 90 98 26 24]


In [ ]:
# 17. Replace values below 50 with 0.
print(np.where(rand_arr < 50, 0, rand_arr))

[51 99  0  0  0 68  0  0 89  0  0 90 65  0 97 55 98  0  0  0]


In [26]:
# 18. Sort the array in ascending and descending order.
print(np.sort(rand_arr))
print(np.sort(rand_arr)[::-1])

[12 14 16 17 21 21 24 26 33 46 49 51 55 65 68 89 90 97 98 99]
[99 98 97 90 89 68 65 55 51 49 46 33 26 24 21 21 17 16 14 12]


In [ ]:
# 19. Find unique values and their frequencies.
uniques, counts = np.unique(rand_arr, return_counts=True)
print(uniques)
print(counts)

In [ ]:
# 20. Create a 5 × 5 random matrix and calculate row-wise and column-wise means.
random_matrix = np.random.rand(5, 5)
print(random_matrix)
print(np.mean(random_matrix, axis=1))
print(np.mean(random_matrix, axis=0))

In [27]:
# 21. Take your own example to normalize an array.  
data = np.array([12, 23, 34, 45, 56], dtype=float)
data_normalized = (data - np.min(data)) / (np.max(data) - np.min(data))
print(data_normalized)

[0.   0.25 0.5  0.75 1.  ]


In [28]:
# 22. use your own data to standardize an array. 
data = np.array([12,23,34,56,67,78], dtype=float)
data_standardized = (data - np.mean(data)) / np.std(data)
print(data_standardized)

[-1.38873015 -0.9258201  -0.46291005  0.46291005  0.9258201   1.38873015]


In [30]:
# 23. Create a NumPy array containing 100 random exam marks and 
# determine how many students fall into the ranges 0–39, 40–59, 60–79, and 80–100.

exam_marks = np.random.randint(0, 101, size=100)

bins = [0, 40, 60, 80, 101]
labels = ["0–39", "40–59", "60–79", "80–100"]
counts, _ = np.histogram(exam_marks, bins=bins)

for label, count in zip(labels, counts):
    print(f"Range {label}: {count} students")

Range 0–39: 43 students
Range 40–59: 17 students
Range 60–79: 16 students
Range 80–100: 24 students


In [31]:
# 24. Compare the time required to multiply 1,000,000 numbers 
# using a Python list and a NumPy array.

import time

size = 1_000_000

# Setup Data
py_list1 = list(range(size))
py_list2 = list(range(size))

np_arr1 = np.arange(size, dtype=np.int64)
np_arr2 = np.arange(size, dtype=np.int64)

# Native Python List Benchmark
start_time = time.time()
py_result = [x * y for x, y in zip(py_list1, py_list2)]
py_time = time.time() - start_time

# NumPy Array Benchmark
start_time = time.time()
np_result = np_arr1 * np_arr2
np_time = time.time() - start_time

print(f"Python List Time: {py_time:.6f} seconds")
print(f"NumPy Array Time: {np_time:.6f} seconds")
print(f"NumPy is ~{py_time / np_time:.2f}x faster.")

Python List Time: 0.108913 seconds
NumPy Array Time: 0.006166 seconds
NumPy is ~17.66x faster.
